# Generated by Django 5.1.4 on 2025-09-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
