apiVersion: apps/v1
kind: Deployment
metadata:
   name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio-container
          image: didin8080/portfolio
          imagePullPolicy: Always
          ports:
           - containerPort: 8000
          env:
           - name: EXTRA_ALLOWED_HOSTS
             value: |
               ae6ea65b3f9ae4f53870799d45ff4dbf-1471619559.us-east-2.elb.amazonaws.com
           - name: POD_IP
             valueFrom:
               fieldRef:
                 fieldPath: status.podIP
      imagePullSecrets:
           - name: regcred
